[versions]
# https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
slf4j = "2.0.13"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
dynatest = "com.github.mvysny.dynatest:dynatest:0.25"
jakarta-servletapi = "jakarta.servlet:jakarta.servlet-api:5.0.0"
javax-servletapi = "javax.servlet:javax.servlet-api:4.0.1"
