[versions]
# https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
slf4j = "2.0.12"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
dynatest = "com.github.mvysny.dynatest:dynatest:0.24"
